insert 
into 
employee
      (id,empno,name,age,birthday,salary,create_by,create_date) 
values
      ('${employee.id}',
       :employee.empno,
       :employee.name,
       :employee.age,
       :employee.birthday,
       :employee.salary,
       :employee.createBy,
       :employee.createDate
      )